### PR TITLE
Add undo and redo functions and isEmpty value

### PR DESCRIPTION
**Pull request by ppamorim**
Hi,

This merge includes the undo and redo functions. Also include the `isEmpty` function to verify the `UIBezierPath` is empty or not.

The undo and redo functions works by storing the `UIBezierPath` when the user touch up in a limited array of 100 items. When the array gets fillfuled, the first item of the array gets removed and so on.

The undo and redo works but it has a bug when you try to undo, draw something and undo again, it's removing the two last `UIBezierPath` in the point of interaction. To simulate the problem you need to:

 - Draw five lines
 - Undo two last lines
 - Draw more 2 different lines
 - Undo these lines again, the undo will behave wrongly.

Would anyone be able to patch this so we can merge this function? Any thoughts?

### CODE REVIEW

**Comment by ppamorim** [comment]
@alankarmisra Any plans to merge this? I  just updated and corrected multiple issues.

**Comment by alankarmisra** [comment]
@ppamorim - gimme until the next weekend to look into it? Sorry, just been away for a bit. Did you manage to fix the bug you mention? Also, is this compatible with PencilKit undo/redo or would we need to add code to do that as well (I have not looked at your code - I apologize if these questions seem redundant - I will definitely look into it soon).

**Comment by ppamorim** [comment]
@alankarmisra I did sort a bunch of issues, you can see the demo running here side by side:

Screenshot 2020-08-16 at 16 27 15

Please be free to test it and find bugs. I am working this to deploy to my product as soon as possible.

Things that I did change:

 - Reduced values of thickness of the demo.
 - Fixed the constraints of the demo app.
 - Now the views and canvas are configured internally only using constraint layout.
 - Undo and Redo functions for both implementations.
 - Swiftlint fixes applied.

**Comment by alankarmisra** [comment]
@ppamorim Sounds fantastic. I'll have a look on the upcoming weekend and merge the changes. Thank you for all the great work!

**Comment by alankarmisra** [comment]
Everything worked great! Thank you again for all the great work!

**Pull request merged**
